name: Test and Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  JAVA_VERSION: 21
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-cleanup: on-success
          
      - name: Make gradlew executable (Unix)
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew
        
      - name: Run Tests
        run: ./gradlew test --no-daemon --stacktrace
        
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.os }}
          path: build/reports/tests/test/

  build:
    name: Build Mod
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-cleanup: on-success
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Build Mod
        run: ./gradlew build --no-daemon --stacktrace
        
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mod-jar-dev
          path: build/libs/*.jar

  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-cleanup: on-success
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest --no-daemon --continue || true
        
      - name: Run SpotBugs
        run: ./gradlew spotbugsMain spotbugsTest --no-daemon --continue || true
        
      - name: Upload Code Quality Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: code-quality-reports
          path: |
            build/reports/checkstyle/
            build/reports/spotbugs/
